# Generated by Django 6.0.4 on 2026-05-11 08:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('floor_number', models.IntegerField()),
                ('status', models.CharField(choices=[('operational', 'operational'), ('maintenance', 'maintenance'), ('degraded', 'degraded'), ('out_of_service', 'out of service')], default='operational', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('technician', 'technician'), ('faculty', 'faculty')], default='faculty', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_code', models.CharField(max_length=20, unique=True)),
                ('operating_system', models.CharField(max_length=30)),
                ('gpu', models.CharField(max_length=30)),
                ('cpu', models.CharField(max_length=30)),
                ('ram_size_installed', models.IntegerField()),
                ('disk_size_installed', models.IntegerField()),
                ('build_version', models.CharField(max_length=30)),
                ('computer_status', models.CharField(choices=[('active', 'active'), ('fixing', 'fixing'), ('broken', 'broken')], default='active', max_length=20)),
                ('monitor_status', models.CharField(choices=[('none', 'none'), ('active', 'active'), ('fixing', 'fixing'), ('broken', 'broken')], default='none', max_length=20)),
                ('mouse_status', models.CharField(choices=[('none', 'none'), ('active', 'active'), ('fixing', 'fixing'), ('broken', 'broken')], default='none', max_length=20)),
                ('keyboard_status', models.CharField(choices=[('none', 'none'), ('active', 'active'), ('fixing', 'fixing'), ('broken', 'broken')], default='none', max_length=20)),
                ('ups_status', models.CharField(choices=[('none', 'none'), ('active', 'active'), ('fixing', 'fixing'), ('broken', 'broken')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('report', 'report'), ('request', 'request')], max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('complaint_description', models.TextField()),
                ('issue_image', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                ('status', models.CharField(choices=[('open', 'open'), ('pending', 'pending'), ('resolved', 'resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.computer')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.room')),
            ],
        ),
    ]
