# Generated by Django 6.0.4 on 2026-05-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
