# Generated by Django 6.0.4 on 2026-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_user_code_alter_room_room_name_repairlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_name',
            field=models.CharField(choices=[('pimentel', 'pimentel'), ('law', 'law'), ('acad', 'acad')], default='pimentel', max_length=20),
        ),
    ]
