# Generated by Django 6.0.4 on 2026-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_maintenancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
