# Generated by Django 6.0.4 on 2026-06-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_report_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('resolved', 'resolved'), ('ongoing', 'ongoing')], default='open', max_length=20),
        ),
    ]
