# Generated by Django 6.0.4 on 2026-06-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='header',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket_type',
            field=models.CharField(choices=[('request', 'request'), ('report', 'report')], default='request', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=20),
        ),
    ]
