# Generated by Django 6.0.4 on 2026-06-23 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_notification_content_notification_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='header',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.report'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='api.ticket'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request', 'request'), ('report', 'report')], default='ticket', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ticket__isnull', False), ('report__isnull', True)), models.Q(('ticket__isnull', True), ('report__isnull', False)), _connector='OR'), name='notif_one_ref'),
        ),
    ]
