# Generated by Django 6.0.4 on 2026-06-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_notification_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
