# Generated by Django 6.0.4 on 2026-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_computer_motherboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
