# Generated by Django 6.0.4 on 2026-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_computer_motherboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='motherboard_status',
            field=models.CharField(choices=[('none', 'none'), ('active', 'active'), ('fixing', 'fixing'), ('broken', 'broken')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(max_length=100),
        ),
    ]
