# Generated by Django 6.0.4 on 2026-07-01 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_computer_motherboard_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='motherboard_status',
        ),
        migrations.AddField(
            model_name='room',
            name='assigned_custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custodian', to=settings.AUTH_USER_MODEL),
        ),
    ]
