# Generated by Django 6.0.4 on 2026-07-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_computer_motherboard_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancehistory',
            name='maintenance_history_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancehistory',
            name='maintenance_type',
            field=models.CharField(choices=[('repair', 'repair'), ('replace', 'replace')], max_length=20),
        ),
    ]
