# Generated by Django 6.0.4 on 2026-07-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_maintenancehistory_maintenance_history_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ticket', 'ticket'), ('report', 'report')], default='ticket', max_length=20),
        ),
    ]
