# Generated by Django 6.0.4 on 2026-07-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notification_receiver_role_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.computer'),
        ),
    ]
