# Generated by Django 6.0.4 on 2026-07-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_ticket_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancehistory',
            name='maintenance_type',
            field=models.CharField(choices=[('repair', 'repair'), ('replace', 'replace'), ('installation', 'installation')], max_length=20),
        ),
    ]
