# Generated by Django 6.0.4 on 2026-07-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_requesthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesthistory',
            name='request_notes',
        ),
    ]
