# Generated by Django 6.0.4 on 2026-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_taskscheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskscheduler',
            name='scheduled_execution',
        ),
        migrations.AddField(
            model_name='taskscheduler',
            name='execution_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskscheduler',
            name='frequency',
            field=models.CharField(choices=[('once', 'once'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='taskscheduler',
            name='last_execution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskscheduler',
            name='next_execution',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskscheduler',
            name='weekday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskscheduler',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
