# Generated by Django 6.0.4 on 2026-07-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_taskscheduler_scheduled_execution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancehistory',
            name='performed_by',
        ),
    ]
