# Generated by Django 6.0.4 on 2026-07-29 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_maintenancehistory_performed_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notif_one_ref',
        ),
        migrations.AddField(
            model_name='notification',
            name='activity_summary',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('ticket', 'ticket'), ('weekly-report', 'weekly-report'), ('computer', 'computer'), ('user', 'user'), ('maintenance_history', 'maintenance_history'), ('room', 'room'), ('request_history', 'request_history'), ('repair_log', 'repair_log')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, choices=[('multicast-admin', 'multicast-admin'), ('multicast-technician', 'multicast-technician'), ('multicast-faculty', 'multicast-faculty'), ('unicast-admin', 'unicast-admin'), ('unicast-technician', 'unicast-technician'), ('unicast-faculty', 'unicast-faculty')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('read', 'read'), ('unread', 'unread')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver_role',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='report',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
