# Generated by Django 6.0.4 on 2026-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_notification_notif_one_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, choices=[('broadcast-admin-technician', 'broadcast-admin-technician'), ('multicast-admin', 'multicast-admin'), ('multicast-technician', 'multicast-technician'), ('multicast-faculty', 'multicast-faculty'), ('unicast-admin', 'unicast-admin'), ('unicast-technician', 'unicast-technician'), ('unicast-faculty', 'unicast-faculty')], max_length=30, null=True),
        ),
    ]
