# Generated by Django 6.0.4 on 2026-07-30 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_notification_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL),
        ),
    ]
