# Generated by Django 6.0.4 on 2026-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, choices=[('multicast-technician', 'multicast-technician'), ('multicast-faculty', 'multicast-faculty'), ('unicast-technician', 'unicast-technician'), ('unicast-faculty', 'unicast-faculty')], max_length=30, null=True),
        ),
    ]
