# Generated by Django 6.0.4 on 2026-08-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_notification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, choices=[('read', 'read'), ('unread', 'unread'), ('archived', 'archived')], max_length=20, null=True),
        ),
    ]
