# Generated by Django 6.0.4 on 2026-08-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auditlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='auditlogs',
            name='action_summary',
            field=models.TextField(),
        ),
    ]
