# Generated by Django 6.0.4 on 2026-08-24 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_userpushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpushtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
