# Generated by Django 6.0.4 on 2026-09-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='reset_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
