# Generated by Django 6.0.4 on 2026-09-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_otpcode_reset_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='reset_token_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
