# Generated by Django 6.0.4 on 2026-09-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_otpcode_reset_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
