# Generated by Django 6.0.4 on 2026-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_otpcode_reset_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='token_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
