# Generated by Django 6.0.4 on 2026-09-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_otpcode_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('resolved', 'resolved'), ('ongoing', 'ongoing'), ('archived', 'archived')], default='open', max_length=20),
        ),
    ]
