# Generated by Django 6.0.4 on 2026-09-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscheduler',
            name='monthday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
