# Generated by Django 6.0.4 on 2026-09-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_printabletemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='computer_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairlog',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('resolved', 'resolved'), ('ongoing', 'ongoing')], default='open', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='computer',
            constraint=models.UniqueConstraint(fields=('room', 'computer_number'), name='unique_computer_number_per_room'),
        ),
    ]
