# Generated by Django 6.0.4 on 2026-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_computer_computer_number_computer_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
