# Generated by Django 6.0.4 on 2026-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_notification_is_archived_notification_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_by',
            field=models.JSONField(default=list),
        ),
    ]
