# Generated by Django 6.0.4 on 2026-09-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_notification_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
    ]
