# Generated by Django 6.0.4 on 2026-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='build_version',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_status',
            field=models.CharField(choices=[('active', 'active'), ('fixing', 'fixing'), ('broken', 'broken')], default='active', max_length=120),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='computer',
            name='gpu',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(max_length=120),
        ),
    ]
