# Generated by Django 6.0.4 on 2026-10-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_computer_build_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_status',
            field=models.CharField(choices=[('active', 'active'), ('unserviceable', 'Unserviceable'), ('pending', 'Pending')], default='active', max_length=120),
        ),
        migrations.AlterField(
            model_name='computer',
            name='keyboard_status',
            field=models.CharField(choices=[('none', 'none'), ('active', 'active'), ('unserviceable', 'Unserviceable'), ('pending', 'Pending')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor_status',
            field=models.CharField(choices=[('none', 'none'), ('active', 'active'), ('unserviceable', 'Unserviceable'), ('pending', 'Pending')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mouse_status',
            field=models.CharField(choices=[('none', 'none'), ('active', 'active'), ('unserviceable', 'Unserviceable'), ('pending', 'Pending')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ups_status',
            field=models.CharField(choices=[('none', 'none'), ('active', 'active'), ('unserviceable', 'Unserviceable'), ('pending', 'Pending')], default='none', max_length=20),
        ),
    ]
