name: iLabCICT Report Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Scheduler Test
        run: |
          echo "Scheduler triggered successfully!"
          date
