name: iLabCICT Report Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Call Scheduler
        run: |
          curl -X GET "${{ secrets.SCHEDULER_URL }}" \
            -H "Authorization: Bearer ${{ secrets.SCHEDULER_TOKEN }}" \
            -H "Content-Type: application/json" \
            --fail \
            --show-error
